# Generated by Django 5.0.4 on 2024-05-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_items_created_at_items_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='updated_at',
        ),
    ]
