# Generated by Django 5.0.4 on 2024-05-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_saveditem_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveditem',
            old_name='item',
            new_name='item_name',
        ),
        migrations.RemoveField(
            model_name='saveditem',
            name='created_at',
        ),
    ]
