# Generated by Django 5.0.4 on 2024-05-04 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_item_saveditem_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
