# Generated by Django 5.0.4 on 2024-05-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_saveditem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditem',
            name='needed_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
